import os
import requests
import datetime
import pathlib
import json

# 🧩 Конфигурация
endpoint = os.getenv("HYBRID_FEEDBACK_ENDPOINT", "http://localhost:9090/api/v1/hybrid/feedback")
token = os.getenv("HYBRID_TOKEN", "mock-token")
headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

# 🗂 Пути для логов и Markdown
docs_path = pathlib.Path("docs/FEEDBACK_STATUS.md")
logs_dir = pathlib.Path("logs")
logs_dir.mkdir(parents=True, exist_ok=True)
log_file = logs_dir / "hybrid_feedback.log"

print(f"🌐 Fetching feedback from Hybrid endpoint: {endpoint}")

# 🛰 Получаем данные от Hybrid API
try:
    response = requests.get(endpoint, headers=headers, timeout=10)
    response.raise_for_status()
    data = response.json()
except Exception as e:
    print(f"❌ Failed to get feedback: {e}")
    with log_file.open("a", encoding="utf-8") as lf:
        lf.write(f"[{datetime.datetime.utcnow()}] ERROR: {e}\n")
    raise SystemExit(1)

timestamp = datetime.datetime.utcnow().isoformat() + "Z"
labs = data.get("labs", [])
summary = data.get("summary", {})

# 🧾 Добавляем запись в лог
with log_file.open("a", encoding="utf-8") as lf:
    lf.write(f"\n[{timestamp}] Feedback sync\n")
    for lab in labs:
        lf.write(
            f"  - {lab.get('name')}: trust={lab.get('trust_score', 0):.2f}, "
            f"status={lab.get('status')}, ready={lab.get('promotion_ready')}\n"
        )
    lf.write(
        f"  Summary: overall_trust={summary.get('overall_trust_index', 0):.2f}, "
        f"eligible={summary.get('eligible_for_promotion', 0)} / "
        f"total={summary.get('total_labs', len(labs))}\n"
    )

print(f"🪵 Feedback log updated → {log_file}")

# 📊 Генерируем таблицу Markdown
table_header = "| 🧪 Lab | 🔒 Trust Score | 📊 Status | 🚀 Promotion Ready | 📝 Notes |\n"
table_header += "|:------|:---------------:|:----------|:------------------:|:---------|\n"

rows = []
for lab in labs:
    rows.append(
        f"| {lab.get('name')} "
        f"| {lab.get('trust_score', 0):.2f} "
        f"| {'✅ validated' if lab.get('status') == 'validated' else '🕓 ' + lab.get('status', 'unknown')} "
        f"| {'✅ yes' if lab.get('promotion_ready') else '❌ no'} "
        f"| {lab.get('notes', '').replace('|', '/')} |"
    )
table = "\n".join(rows)

summary_table = (
    "| Metric | Value |\n"
    "|:--------|:------|\n"
    f"| Total Labs | {summary.get('total_labs', len(labs))} |\n"
    f"| Eligible for Promotion | {summary.get('eligible_for_promotion', 0)} |\n"
    f"| Overall Trust Index | {summary.get('overall_trust_index', 0):.2f} |\n"
)

# 🧱 Markdown шаблон
content = f"""# 🔁 Hybrid Feedback Status

_Last sync: **{timestamp} UTC**_

---

## 🧠 Overview

This dashboard is automatically generated by  
`Hybrid Feedback Listener (v1)` — synchronizing lab trust and promotion readiness from Hybrid.

| Field | Description |
|:------|:-------------|
| `trust_score` | Numerical trust index (0–1.0) |
| `status` | Lab security validation stage |
| `promotion_ready` | Indicates if lab can move up from sandbox |
| `notes` | Short summary of Hybrid feedback pipeline |

---

## 🧩 Latest Feedback Snapshot

{table_header}{table}

---

## 📈 Summary

{summary_table}

---

### 🧾 Historical Log Reference
The full feedback history is available in:  
`logs/hybrid_feedback.log`

---

### 🧩 Next Update
Synced every **15 minutes** or via manual trigger  
**Actions → 🔁 Hybrid Feedback Listener (v1)**

_Last updated automatically by `scripts/pull_hybrid_feedback.py`_
"""

# 📝 Сохраняем Markdown
docs_path.write_text(content, encoding="utf-8")
print(f"✅ Markdown dashboard updated → {docs_path}")
