import os
import requests
import datetime
import pathlib
import json
import re

# 🧩 Конфигурация
endpoint = os.getenv("HYBRID_FEEDBACK_ENDPOINT", "http://localhost:9090/api/v1/hybrid/feedback")
token = os.getenv("HYBRID_TOKEN", "mock-token")
headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

# 🗂 Пути
docs_path = pathlib.Path("docs/FEEDBACK_STATUS.md")
logs_dir = pathlib.Path("logs")
logs_dir.mkdir(parents=True, exist_ok=True)
log_file = logs_dir / "hybrid_feedback.log"

print(f"🌐 Fetching feedback from Hybrid endpoint: {endpoint}")

# 🛰 Получение данных
try:
    response = requests.get(endpoint, headers=headers, timeout=10)
    response.raise_for_status()
    data = response.json()
except Exception as e:
    print(f"❌ Failed to get feedback: {e}")
    with log_file.open("a", encoding="utf-8") as lf:
        lf.write(f"[{datetime.datetime.utcnow()}] ERROR: {e}\n")
    raise SystemExit(1)

timestamp = datetime.datetime.utcnow().isoformat() + "Z"
labs = data.get("labs", [])
summary = data.get("summary", {})

# 🧠 Считываем предыдущие trust_score из логов
previous_scores = {}
if log_file.exists():
    try:
        content = log_file.read_text(encoding="utf-8")
        matches = re.findall(r"- (\w+): trust=([0-9.]+)", content)
        for lab, score in matches[-10:]:  # анализируем последние 10 записей
            previous_scores[lab] = float(score)
    except Exception:
        pass

# 🧾 Логирование новой сессии
with log_file.open("a", encoding="utf-8") as lf:
    lf.write(f"\n[{timestamp}] Feedback sync\n")
    for lab in labs:
        lf.write(
            f"  - {lab.get('name')}: trust={lab.get('trust_score', 0):.2f}, "
            f"status={lab.get('status')}, ready={lab.get('promotion_ready')}\n"
        )
    lf.write(
        f"  Summary: overall_trust={summary.get('overall_trust_index', 0):.2f}, "
        f"eligible={summary.get('eligible_for_promotion', 0)} / "
        f"total={summary.get('total_labs', len(labs))}\n"
    )

print(f"🪵 Log updated → {log_file}")

# 📊 Генерация Markdown таблицы с сравнением trust_score
table_header = "| 🧪 Lab | 🔒 Trust Score | 📊 Status | 🚀 Promotion Ready | 🧭 Change | 📝 Notes |\n"
table_header += "|:------|:---------------:|:----------|:------------------:|:---------:|:---------|\n"

rows = []
for lab in labs:
    name = lab.get("name")
    current_score = lab.get("trust_score", 0)
    prev_score = previous_scores.get(name)
    delta = None
    trend = ""

    if prev_score is not None:
        delta = round(current_score - prev_score, 3)
        if delta < -0.02:
            trend = f"⚠️ ↓{abs(delta):.2f}"
        elif delta > 0.02:
            trend = f"🟢 ↑{delta:.2f}"
        else:
            trend = "➖ stable"
    else:
        trend = "🆕 new"

    rows.append(
        f"| {name} "
        f"| {current_score:.2f} "
        f"| {'✅ validated' if lab.get('status') == 'validated' else '🕓 ' + lab.get('status', 'unknown')} "
        f"| {'✅ yes' if lab.get('promotion_ready') else '❌ no'} "
        f"| {trend} "
        f"| {lab.get('notes', '').replace('|', '/')} |"
    )
table = "\n".join(rows)

summary_table = (
    "| Metric | Value |\n"
    "|:--------|:------|\n"
    f"| Total Labs | {summary.get('total_labs', len(labs))} |\n"
    f"| Eligible for Promotion | {summary.get('eligible_for_promotion', 0)} |\n"
    f"| Overall Trust Index | {summary.get('overall_trust_index', 0):.2f} |\n"
)

# 🧱 Markdown отчёт
content = f"""# 🔁 Hybrid Feedback Status

_Last sync: **{timestamp} UTC**_

---

## 🧠 Overview

This file is automatically generated by  
**Hybrid Feedback Listener (Enterprise v2)** — with trust trend analysis and promotion readiness.

| Field | Description |
|:------|:-------------|
| `trust_score` | Numerical trust index (0–1.0) |
| `status` | Lab validation stage |
| `promotion_ready` | Indicates if lab can move up from sandbox |
| `change` | Trust delta since last sync |
| `notes` | Remarks from Hybrid feedback pipeline |

---

## 🧩 Latest Feedback Snapshot

{table_header}{table}

---

## 📈 Summary

{summary_table}

---

### 🧾 Historical Log Reference
See detailed trust history at:  
`logs/hybrid_feedback.log`

---

### 🧩 Next Update
Synced every **15 minutes** or on manual trigger via  
**Actions → 🔁 Hybrid Feedback Listener (v1)**

_Last updated automatically by `scripts/pull_hybrid_feedback.py`_
"""

docs_path.write_text(content, encoding="utf-8")
print(f"✅ Markdown dashboard updated with trust delta → {docs_path}")
