import os
import requests
import datetime
import pathlib
import json

# 🧩 Конфигурация
endpoint = os.getenv("HYBRID_FEEDBACK_ENDPOINT", "http://localhost:9090/api/v1/hybrid/feedback")
token = os.getenv("HYBRID_TOKEN", "mock-token")
headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

print(f"🌐 Fetching feedback from Hybrid endpoint: {endpoint}")

# 🛰 Получение данных от Hybrid
try:
    response = requests.get(endpoint, headers=headers, timeout=10)
    response.raise_for_status()
    data = response.json()
except Exception as e:
    print(f"❌ Failed to get feedback: {e}")
    raise SystemExit(1)

timestamp = datetime.datetime.utcnow().isoformat() + "Z"
labs = data.get("labs", [])
summary = data.get("summary", {})

# 📊 Генерация таблицы лабораторий
table_header = "| 🧪 Lab | 🔒 Trust Score | 📊 Status | 🚀 Promotion Ready | 📝 Notes |\n"
table_header += "|:------|:---------------:|:----------|:------------------:|:---------|\n"

rows = []
for lab in labs:
    rows.append(
        f"| {lab.get('name')} "
        f"| {lab.get('trust_score', 0):.2f} "
        f"| {'✅' if lab.get('status') == 'validated' else '🕓 ' + lab.get('status', 'unknown')} "
        f"| {'✅ yes' if lab.get('promotion_ready') else '❌ no'} "
        f"| {lab.get('notes', '')} |"
    )
table = "\n".join(rows)

# 📈 Таблица Summary
summary_table = (
    "| Metric | Value |\n"
    "|:--------|:------|\n"
    f"| Total Labs | {summary.get('total_labs', len(labs))} |\n"
    f"| Eligible for Promotion | {summary.get('eligible_for_promotion', 0)} |\n"
    f"| Overall Trust Index | {summary.get('overall_trust_index', 0):.2f} |\n"
)

# 🧱 Markdown-шаблон
content = f"""# 🔁 Hybrid Feedback Status

_Last sync: **{timestamp} UTC**_

---

## 🧠 Overview

This file is automatically generated by  
`Hybrid Feedback Listener (v1)` — pulling lab trust data from Hybrid mock or live orchestrator.

| Field | Description |
|:------|:-------------|
| `trust_score` | Numerical trust index (0–1.0) |
| `status` | Lab security validation stage |
| `promotion_ready` | Indicates if lab can move up from sandbox |
| `notes` | Brief remarks from Hybrid feedback pipeline |

---

## 🧩 Latest Feedback Snapshot

{table_header}{table}

---

## 📈 Summary

{summary_table}

---

### 🧩 Next Update
Synced every **15 minutes** or on manual trigger via  
**Actions → 🔁 Hybrid Feedback Listener (v1)**

_Last updated automatically by `scripts/pull_hybrid_feedback.py`_
"""

# 📁 Запись файла
output_path = pathlib.Path("docs/FEEDBACK_STATUS.md")
output_path.write_text(content, encoding="utf-8")

print(f"✅ Feedback dashboard updated at {output_path}")
